# Generated by Django 5.0.1 on 2024-05-29 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cours', '0002_cours_heure_cours_jour'),
    ]

    operations = [
        migrations.CreateModel(
            name='professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=20)),
                ('telephone', models.IntegerField()),
                ('cours', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cours.cours')),
            ],
        ),
    ]
