# Generated by Django 5.0.1 on 2024-05-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='nom',
        ),
        migrations.AddField(
            model_name='salle',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salle',
            name='batiment',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1),
        ),
    ]
